### ISSUE TITLE
yobo requires that the superset has extended the same backbone as 'backbone-filtered-collection requires

### ISSUE THREAD

**Issue by atamon** [Yolean/yobo#6]
Otherwise the subset will believe that the provided models are not actually models, but JSON blobs, and it will create another model instance to wrap these existing models. Modelception!

This becomes an issue when you have multiple backbone modules in your node_modules tree. For example when you've got yobo linked in your file tree.

If you get creative you can work around it though. And once you install yobo directly this is not a real issue any longer.

**Comment by solsson** [comment]
This is another instance of why we need bullet #4 (in the readme, but I created an empty issue for it). I think it is backbone's `instanceof Model` that is the problem in an npm/webpack environment. In current https://github.com/jashkenas/backbone master they have extracted an _isModel. Could we safely override it with `typeof model.attributes !== 'undefined'`?

On the other hand I think we should try to use a single backbone import, as it reduced the size of the webpack bundles. That's why I did the export of `yobo.Backbone` in addition to `yobo.Model` and `yobo.Collection`.

**Comment by atamon** [comment]
Overwriting internal (_prefixed attributes) is likely to break without us knowing it (a patch or minor bump which removes usage of the attribute for example). So I would avoid this if we can. npm has a dedupe feature just for these type of issues (I assume), see https://docs.npmjs.com/cli/dedupe for more info. Maybe it will take us far enough and this won't be a practical problem for us.

I sort of agree with your second paragraph, but in many of Yolean's applications this would imply having live-backbone depend on yobo. Which might be something we wish to support, especially the case where live-backbone is just another of yobo's mixins. But this is probably not happening in the near future.

**Comment by solsson** [comment]
Webpack also has dedupe. Could do the trick.

However, I'm not a big fan of subclassing, and `instanceof`in js is a pretty strong requirement while runtime API compatibility is what you actually want to check for. Basically a backbone model should have .attributes, .set, .get and events. Why force every model definition to have access to a Backbone.Model and extend from there. Backbone Events is documented as a mixin easy to add using the https://github.com/Reposoft/bev strategy.

Backbone 1.2.0 has been released and there's now an overridable `_isModel` (http://backbonejs.org/docs/backbone.html#section-142). Worth investigating.
